"""initial schema

Revision ID: 88eeaa731b94
Revises: 
Create Date: 2026-02-09 13:25:20.066574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88eeaa731b94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('six_three_five_skipped', sa.Boolean(), nullable=True),
    sa.Column('owner_participant_uuid', sa.String(length=36), nullable=True),
    sa.Column('collaborative_consultation', sa.Boolean(), nullable=True),
    sa.Column('user_role', sa.String(length=30), nullable=True),
    sa.Column('reflections', sa.Text(), nullable=True),
    sa.Column('expert_mode', sa.Boolean(), nullable=True),
    sa.Column('prompt_language', sa.String(length=5), nullable=True),
    sa.Column('custom_prompts', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_api_base', sa.String(length=255), nullable=True),
    sa.Column('company_profile', sa.Text(), nullable=True),
    sa.Column('idea_clusters', sa.Text(), nullable=True),
    sa.Column('selected_cluster_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_uuid'), ['session_uuid'], unique=True)

    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('info_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_info_id'), ['id'], unique=False)

    op.create_table('consultation_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('factor_type', sa.String(length=50), nullable=False),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'factor_type', name='_session_factor_uc')
    )
    with op.batch_alter_table('consultation_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_findings_id'), ['id'], unique=False)

    op.create_table('maturity_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resources_score', sa.Float(), nullable=True),
    sa.Column('resources_details', sa.Text(), nullable=True),
    sa.Column('information_systems_score', sa.Float(), nullable=True),
    sa.Column('information_systems_details', sa.Text(), nullable=True),
    sa.Column('culture_score', sa.Float(), nullable=True),
    sa.Column('culture_details', sa.Text(), nullable=True),
    sa.Column('organizational_structure_score', sa.Float(), nullable=True),
    sa.Column('organizational_structure_details', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('maturity_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_assessments_id'), ['id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_participant_uuid'), ['participant_uuid'], unique=True)

    op.create_table('consultation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_messages_id'), ['id'], unique=False)

    op.create_table('finding_cross_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_finding_id', sa.Integer(), nullable=False),
    sa.Column('target_finding_type', sa.String(length=50), nullable=False),
    sa.Column('linked_phrase', sa.String(length=500), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_finding_id'], ['consultation_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_cross_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_cross_references_id'), ['id'], unique=False)

    op.create_table('idea_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sheet_number', sa.Integer(), nullable=False),
    sa.Column('current_participant_id', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['current_participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sheet_number', name='_session_sheet_uc')
    )
    with op.batch_alter_table('idea_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_sheets_id'), ['id'], unique=False)

    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('idea_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['idea_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ideas_id'), ['id'], unique=False)

    op.create_table('prioritizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('vote_type', sa.String(length=50), nullable=True),
    sa.Column('vote_phase', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prioritizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prioritizations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prioritizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prioritizations_id'))

    op.drop_table('prioritizations')
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ideas_id'))

    op.drop_table('ideas')
    with op.batch_alter_table('idea_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_sheets_id'))

    op.drop_table('idea_sheets')
    with op.batch_alter_table('finding_cross_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_cross_references_id'))

    op.drop_table('finding_cross_references')
    with op.batch_alter_table('consultation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_messages_id'))

    op.drop_table('consultation_messages')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_participant_uuid'))
        batch_op.drop_index(batch_op.f('ix_participants_id'))

    op.drop_table('participants')
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_assessments_id'))

    op.drop_table('maturity_assessments')
    with op.batch_alter_table('consultation_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_findings_id'))

    op.drop_table('consultation_findings')
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_info_id'))

    op.drop_table('company_info')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_uuid'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
